version: "3.9"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
      - programming-ui
    ports:
      - 7800:7800

  programming-api:
    build: 
      context: programming-api
      dockerfile: Dockerfile.prod
    image: programming-api-prod
    restart: "on-failure"
    volumes:
      - ./programming-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  programming-ui:
    build: programming-ui
    image: programming-ui
    restart: "no"
    volumes:
      - ./programming-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - programming-api

  grader-api:
    build: 
      context: grader-api
      dockerfile: Dockerfile.prod
    image: grader-api
    restart: "on-failure"
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000

  database:
    container_name: database-server-dab-p1-86fc96fa-9f67-43c2-8ed5-70b00db4b57c
    image: postgres:14.1
    restart: "unless-stopped"
    volumes: 
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:10.0.1-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
    profiles: 
      - test